namespace: visiosto
name: common
version: 0.1.0
readme: README.md
authors:
  - Visiosto oy <visiosto@visiosto.fi> (https://www.visiosto.fi)
description: Shared resources for Ansible playbooks
license:
  - MIT
dependencies:
  devsec.hardening: ">=10.3.0,<11.0.0"
repository: https://github.com/visiosto/visiosto.common.git
documentation: https://github.com/visiosto/visiosto.common
homepage: https://github.com/visiosto/visiosto.common
issues: https://github.com/visiosto/visiosto.common/issues
build_ignore: []
