---
collections:
  - name: ansible.posix
    version: ">=2.0.0,<3.0.0"
  - name: community.general
    version: ">=10.5.0,<11.0.0"
  - name: devsec.hardening
    version: ">=10.3.0,<11.0.0"
roles:
  - name: nginxinc.nginx
    version: 0.25.0
  - name: geerlingguy.ntp
    version: 2.7.0
