---
- name: Reload firewalld
  listen: firewalld_reload
  ansible.builtin.systemd_service:
    name: firewalld
    state: reloaded
  when: ansible_facts.os_family == "RedHat"

- name: Reload UFW
  listen: ufw_reload
  community.general.ufw:
    state: reloaded
  when: ansible_facts.os_family == "Debian"
