---
- name: Require manual definition of remote-user
  ansible.builtin.fail:
    msg: |
      When using `--ask-pass` option, use `-u` option to define remote-user:
      ansible-playbook server.yml -e env={{ env | default('production') }} -u root --ask-pass
  when:
    dynamic_user | default(true) and ansible_user is not defined and
    cli_ask_pass | default(false)
# vi: ft=yaml.ansible
