---
- name: Update firewall package
  ansible.builtin.apt:
    name: ufw
    state: "{{ firewall_package_state }}"
    cache_valid_time: "{{ firewall_package_cache_valid_time }}"

- name: Enable firewall
  community.general.ufw:
    state: enabled
    default: deny

- name: Set allowed ports
  community.general.ufw:
    rule: allow
    to_port: "{{ item.key }}"
    proto: "{{ item.value }}"
  loop: "{{ ufw_allowed_ports | dict2items }}"
